"""Add sentiment analysis columns

Revision ID: 34946fb9b3bd
Revises: 7711754212c5
Create Date: 2025-05-14 11:24:11.139725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34946fb9b3bd'
down_revision = '7711754212c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_article', schema=None) as batch_op:
        batch_op.drop_column('confidence')
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
